name: Generate Snake

# Controls when the action will run. This action runs every 12 hours.
on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Generates the snake  
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ayahack89
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Show the status of the build. Makes it easier to debug if there are any issues.
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
          force: true

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
